// admin-panel-nuxt/pages/customers/index.vue
<template>
  <div>
    <v-row class="mb-4">
      <v-col cols="12">
        <h1 class="text-h4">Клиенты</h1>
      </v-col>
    </v-row>

    <v-card>
      <v-card-title>
        <v-text-field
          v-model="search"
          prepend-inner-icon="mdi-magnify"
          label="Поиск по имени, email, телефону"
          single-line
          hide-details
          variant="outlined"
          density="compact"
          class="mb-4"
        ></v-text-field>
      </v-card-title>

      <v-data-table
        :headers="headers"
        :items="customers"
        :loading="loading"
        :items-per-page="pagination.perPage"
        :page="pagination.page"
        :server-items-length="total"
        @update:page="handlePageChange"
        @update:items-per-page="handlePerPageChange"
        @click:row="handleRowClick"
      >
        <template v-slot:item.createdAt="{ item }">
          {{ formatDate(item.createdAt) }}
        </template>

        <template v-slot:item.address="{ item }">
          <div style="max-width: 200px; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical">
            {{ item.address || '-' }}
          </div>
        </template>

        <template v-slot:item.tags="{ item }">
          <div style="display: flex; gap: 4px; flex-wrap: wrap">
            <v-chip
              v-for="(tag, index) in (item.tags || []).slice(0, 3)"
              :key="index"
              size="small"
              variant="outlined"
            >
              {{ tag }}
            </v-chip>
          </div>
        </template>

        <template v-slot:item.stats="{ item }">
          <div>
            <div>Заказов: {{ item._count?.orders || 0 }}</div>
            <div class="text-caption text-grey">Отзывов: {{ item._count?.reviews || 0 }}</div>
          </div>
        </template>

        <template v-slot:item.actions="{ item }">
          <v-btn
            icon="mdi-eye"
            size="small"
            variant="text"
            @click.stop="navigateTo({ name: 'customers-id', params: { id: item.id } })"
          ></v-btn>
          <v-btn
            icon="mdi-pencil"
            size="small"
            variant="text"
            @click.stop="navigateTo({ name: 'customers-edit-id', params: { id: item.id } })"
          ></v-btn>
        </template>
      </v-data-table>
    </v-card>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useApi } from '~/composables/useApi'

definePageMeta({
  middleware: 'auth'
})

const api = useApi()
const loading = ref(false)
const customers = ref([])
const total = ref(0)
const search = ref('')

const pagination = reactive({
  page: 1,
  perPage: 25
})

const headers = [
  { title: 'Дата регистрации', key: 'createdAt', sortable: true },
  { title: 'Имя', key: 'name', sortable: true },
  { title: 'Email', key: 'email', sortable: true },
  { title: 'Телефон', key: 'phone', sortable: true },
  { title: 'Адрес', key: 'address', sortable: false },
  { title: 'Теги', key: 'tags', sortable: false },
  { title: 'Статистика', key: 'stats', sortable: false },
  { title: 'Активен', key: 'isActive', sortable: true },
  { title: 'Действия', key: 'actions', sortable: false }
]

const formatDate = (date) => {
  if (!date) return 'Не указана'
  return new Date(date).toLocaleString('ru-RU', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const loadCustomers = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.page,
      limit: pagination.perPage,
      sortBy: 'createdAt',
      sortOrder: 'desc'
    }

    if (search.value) {
      params.search = search.value
    }

    const response = await api.getList('customers', params)
    customers.value = response.data
    total.value = response.total
  } catch (error) {
    console.error('Ошибка загрузки клиентов:', error)
  } finally {
    loading.value = false
  }
}

const handlePageChange = (page) => {
  pagination.page = page
  loadCustomers()
}

const handlePerPageChange = (perPage) => {
  pagination.perPage = perPage
  pagination.page = 1
  loadCustomers()
}

const handleRowClick = (event, row) => {
  navigateTo({ name: 'customers-edit-id', params: { id: row.item.id } })
}

const debounce = (fn, delay) => {
  let timeoutId
  return (...args) => {
    clearTimeout(timeoutId)
    timeoutId = setTimeout(() => fn(...args), delay)
  }
}

const debouncedSearch = debounce(() => {
  pagination.page = 1
  loadCustomers()
}, 500)

watch(search, () => {
  debouncedSearch()
})

onMounted(() => {
  loadCustomers()
})
</script>

// admin-panel/src/resources/customers.tsx
import {
    List,
    Datagrid,
    TextField,
    EmailField,
    Edit,
    SimpleForm,
    TextInput,
    required,
    Show,
    SimpleShowLayout,
    DateField,
    SearchInput,
    FilterButton,
    TopToolbar,
    FunctionField,
    BooleanField,
    ArrayInput,
    SimpleFormIterator
} from 'react-admin';
import { Box, Typography, Chip } from '@mui/material';

// Фильтры
const customerFilters = [
    <SearchInput source="search" placeholder="Поиск по имени, email, телефону" alwaysOn />,
];

// Действия в тулбаре
const CustomerListActions = () => (
    <TopToolbar>
        <FilterButton />
    </TopToolbar>
);

export const CustomerList = () => (
    <List
        title="Клиенты"
        filters={customerFilters}
        actions={<CustomerListActions />}
        sort={{ field: 'createdAt', order: 'DESC' }}
        perPage={25}
    >
        <Datagrid rowClick="edit" sx={{ '& .RaDatagrid-headerCell': { fontWeight: 'bold' } }}>
            <DateField source="createdAt" label="Дата регистрации" showTime />
            <TextField source="name" label="Имя" />
            <EmailField source="email" label="Email" />
            <TextField source="phone" label="Телефон" />
            <FunctionField
                label="Адрес"
                render={(record: any) => (
                    <Box sx={{ maxWidth: 200 }}>
                        <Typography variant="body2" sx={{
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            display: '-webkit-box',
                            WebkitLineClamp: 2,
                            WebkitBoxOrient: 'vertical'
                        }}>
                            {record.address || '-'}
                        </Typography>
                    </Box>
                )}
            />
            <FunctionField
                label="Теги"
                render={(record: any) => (
                    <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                        {record.tags && record.tags.length > 0 ? (
                            record.tags.slice(0, 3).map((tag: string, index: number) => (
                                <Chip key={index} label={tag} size="small" />
                            ))
                        ) : (
                            <Typography variant="body2" color="text.secondary">-</Typography>
                        )}
                    </Box>
                )}
            />
            <FunctionField
                label="Статистика"
                render={(record: any) => (
                    <Box>
                        <Typography variant="body2">
                            Заказов: {record._count?.orders || 0}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                            Отзывов: {record._count?.reviews || 0}
                        </Typography>
                    </Box>
                )}
            />
            <BooleanField source="isActive" label="Активен" />
        </Datagrid>
    </List>
);

export const CustomerEdit = () => (
    <Edit title="Редактировать клиента">
        <SimpleForm>
            <Box display="flex" gap={2} width="100%">
                <Box flex={1}>
                    <Typography variant="h6" gutterBottom>Основная информация</Typography>
                    <TextInput disabled source="id" fullWidth />
                    <TextInput source="name" label="Имя" fullWidth validate={[required()]} />
                    <TextInput source="email" label="Email" fullWidth type="email" />
                    <TextInput source="phone" label="Телефон" fullWidth validate={[required()]} />
                    <TextInput
                        source="address"
                        label="Адрес"
                        fullWidth
                        multiline
                        rows={2}
                    />
                </Box>

                <Box flex={1}>
                    <Typography variant="h6" gutterBottom>Дополнительная информация</Typography>
                    <TextInput
                        source="notes"
                        label="Примечания"
                        fullWidth
                        multiline
                        rows={4}
                    />
                    <ArrayInput source="tags" label="Теги">
                        <SimpleFormIterator>
                            <TextInput source="" label="Тег" />
                        </SimpleFormIterator>
                    </ArrayInput>
                    <BooleanField source="isActive" label="Активен" />
                    <DateField source="createdAt" label="Дата регистрации" showTime />
                    <DateField source="updatedAt" label="Последнее обновление" showTime />
                </Box>
            </Box>
        </SimpleForm>
    </Edit>
);

export const CustomerShow = () => (
    <Show title="Просмотр клиента">
        <SimpleShowLayout>
            <TextField source="name" label="Имя" />
            <EmailField source="email" label="Email" />
            <TextField source="phone" label="Телефон" />
            <TextField source="address" label="Адрес" />
            <TextField source="notes" label="Примечания" />
            <FunctionField
                label="Теги"
                render={(record: any) => (
                    <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                        {record.tags && record.tags.length > 0 ? (
                            record.tags.map((tag: string, index: number) => (
                                <Chip key={index} label={tag} size="small" />
                            ))
                        ) : (
                            <Typography variant="body2" color="text.secondary">Нет тегов</Typography>
                        )}
                    </Box>
                )}
            />
            <BooleanField source="isActive" label="Активен" />
            <DateField source="createdAt" label="Дата регистрации" showTime />
            <DateField source="updatedAt" label="Последнее обновление" showTime />
            <FunctionField
                label="Статистика"
                render={(record: any) => (
                    <Box>
                        <Typography variant="body1" gutterBottom>
                            Заказов: {record._count?.orders || 0}
                        </Typography>
                        <Typography variant="body1" gutterBottom>
                            Отзывов: {record._count?.reviews || 0}
                        </Typography>
                        <Typography variant="body1">
                            Обратных звонков: {record._count?.callbacks || 0}
                        </Typography>
                    </Box>
                )}
            />
        </SimpleShowLayout>
    </Show>
);
